server:
  port: 99
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://192.168.200.129:3306/chongba_order_trade
        username: root
    redis:
        host: 192.168.200.129
        password: chongba
        port: 6379
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 5000 
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
rocketmq:
    name-server: 192.168.200.129:9876
    producer:
        group: chongba-group
        
supplier:
  apis: {
          "jisuapi": "http://127.0.0.1:8090/jisuapi/mobilerecharge/recharge",
          "juheapi": "http://127.0.0.1:8090/juheapi/recharge"
         } 
  maxrepeat: 4 #最大重试次数       