# 端口
server.port: 10010
# 当前应用的名称
spring.application.name: gateway-server
# 注册中心的地址
eureka.client.service-url.defaultZone: http://127.0.0.1:10086/eureka

# 配置路由转发的规则
spring:
  cloud:
    gateway:
      # 全局过滤器：对所有的路由都生效的过滤器
      default-filters:
        - AddResponseHeader=i-love,java
      routes:
        # 当前路由的唯一标识
        - id: user-service-route1
          # 转发到服务的地址http://127.0.0.1:9091
          ##uri: http://127.0.0.1:9091
          # 配置动态路由lb://{服务的名称}
          uri: lb://user-service
          # 断言，当前路由转发的规则(拦截规则)
          ## http://127.0.0.1:9091/user/xx
          predicates:
            #- Path=/user/**
            - Path=/**
          # 局部过滤器，对当前路由(1)生效的过滤器
          filters:
            # 添加前缀
            # http://127.0.0.1:10010/findById?id=1   == > http://127.0.0.1:9091/user/findById?id=1
            # - PrefixPath=/user
            - StripPrefix=1


